#!/usr/bin/expect -f

set timeout -1 
spawn npx sb init;
expect {
  {Ok to proceed? (y) } {
    send "y\r";
    exp_continue
  }
  -re "\\?.*Do you want to run the.*eslintPlugin.*migration on your project\\?.*" {
    send "y\r";
  }
}
expect eof
